# These are supported funding model platforms

github: [TrustsMotion]

patreon: trusts_motion

open_collective: swi-project

ko_fi: trusts_motion

tidelift:

community_bridge:

liberapay: trusts_motion

issuehunt:

lfx_crowdfunding:

polar:

buy_me_a_coffee: trusts_motion

thanks_dev:

custom:
  - "https://github.com/sponsors/TrustsMotion"
  - "https://swi-project.org/support"
  - "https://github.com/TrustsMotion/SWI"
