"""Independent integrity derivation (SWI-GOV-REMEDIATION-001 §4).

Integrity is calculated or compared by the verifier.
It is never accepted as an input boolean authority.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Optional

from .halt import halt


def _canonical(obj: Any) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def sha256_of(data: str | bytes) -> str:
    if isinstance(data, str):
        data = data.encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def verify_integrity(
    module_id: str,
    *,
    expected_commit: Optional[str] = None,
    actual_commit: Optional[str] = None,
    expected_contract_sha256: Optional[str] = None,
    actual_contract_sha256: Optional[str] = None,
    contract_content: Optional[str] = None,
) -> dict[str, Any]:
    """Derive/compare integrity. Return evidence or HALT.

    "verified": true is generated by this function only.
    """
    # Reject pure assertion path (caller must not pass integrity_verified as authority)
    results = {
        "integrity": {
            "algorithm": "SHA-256",
            "expected": {},
            "observed": {},
            "verified": False,
        }
    }

    has_commit = expected_commit is not None and actual_commit is not None
    has_contract = expected_contract_sha256 is not None and actual_contract_sha256 is not None

    # Optional: if raw contract content is supplied, recalculate its hash
    if contract_content is not None:
        calculated = sha256_of(contract_content)
        results["integrity"]["observed"]["contract_sha256_calculated"] = calculated
        if expected_contract_sha256 is not None and calculated != expected_contract_sha256:
            return halt(
                module_id,
                "CONTRACT_CONTENT_HASH_MISMATCH",
                expected_contract_sha256,
                calculated,
                contract_sha256=calculated,
            )
        # Treat calculated as the observed value
        actual_contract_sha256 = calculated
        has_contract = expected_contract_sha256 is not None

    if not has_commit and not has_contract:
        return halt(
            module_id,
            "INTEGRITY_FIELDS_MISSING",
            "expected/actual commit and/or contract hash",
            "absent",
        )

    if has_commit:
        results["integrity"]["expected"]["commit"] = expected_commit
        results["integrity"]["observed"]["commit"] = actual_commit
        if expected_commit != actual_commit:
            return halt(
                module_id,
                "COMMIT_MISMATCH",
                str(expected_commit),
                str(actual_commit),
                commit=str(actual_commit),
            )

    if has_contract:
        results["integrity"]["expected"]["contract_sha256"] = expected_contract_sha256
        results["integrity"]["observed"]["contract_sha256"] = actual_contract_sha256
        if expected_contract_sha256 != actual_contract_sha256:
            return halt(
                module_id,
                "CONTRACT_HASH_MISMATCH",
                str(expected_contract_sha256),
                str(actual_contract_sha256),
                contract_sha256=str(actual_contract_sha256),
            )

    results["integrity"]["verified"] = True  # generated by verifier only
    results["ok"] = True
    return results
